namespace foodApp.Services;

public static class MockApiConfig
{
    // Replace with the Resource endpoint generated by mockapi.io.
    // Example: https://682xxxx.mockapi.io/api/v1/foods
    public const string EndpointUrl = "";

    public static bool IsConfigured => !string.IsNullOrWhiteSpace(EndpointUrl);
}
