namespace foodApp.Services;

public static class MockApiConfig
{
    // Replace with the Resource endpoint generated by mockapi.io.
    public const string EndpointUrl = "https://69f8bf8ef7044aa0103e6d42.mockapi.io/foods";

    public static bool IsConfigured => !string.IsNullOrWhiteSpace(EndpointUrl);
}
