namespace foodApp.Services;

public static class MockApiConfig
{
    // Replace with the Resource endpoints generated by mockapi.io.
    public const string FoodsEndpointUrl = "https://69f8bf8ef7044aa0103e6d42.mockapi.io/foods";
    public const string UsersEndpointUrl = "https://69f8bf8ef7044aa0103e6d42.mockapi.io/users";

    public static bool IsFoodsConfigured => !string.IsNullOrWhiteSpace(FoodsEndpointUrl);
    public static bool IsUsersConfigured => !string.IsNullOrWhiteSpace(UsersEndpointUrl);

    // Legacy alias
    public static bool IsConfigured => IsFoodsConfigured;
    public static string EndpointUrl => FoodsEndpointUrl;
}
